Farm hut update
ldtteam/MinecoloniesWiki pull request #765
Opened 2022-04-13 13:32 UTC by Nikademus

Closes #

## Changes proposed:
- Updating farm images
- Updating farm page to use @Thodor12 new page code
- change to apiary page to display page specific image for settings
- change to settings includes to display options
- Update fisher hut
- Update fletcher

Merge please :D

2022-04-13 13:49 UTC, Thodor12 requested changes

2022-04-13 13:49 UTC, Thodor12 commented on _includes/contentblock/stock-gui.html
> +        <img src="{{ include.image }}" class="img-fluid mx-auto" alt="{{ include.alt | default: 'Minimum stock GUI' | strip }}">
Probably want to change `{{ include.image }}` to `{{ include.image | default: '../../assets/images/gui/minstockgui.png' }}`

2022-04-13 15:10 UTC, Thodor12 commented
Tested locally and it works now

2022-04-13 16:57 UTC, Thodor12 requested changes

2022-04-14 05:43 UTC, anonymous563 approved these changes

2022-04-14 05:44 UTC, merged