Project restructuring
ldtteam/MinecoloniesWiki pull request #771
Opened 2022-04-16 20:45 UTC by Thodor12

## Changes proposed:
- The current structure has a few problems which this PR aims to resolve:
   - Root level files (like crowdin.yml) are unnecessarily published because the Jekyll source root is `.`.
   - Testing locally is not possible because the Jekyll binaries are not provided, I've added a `GemFile` into the project and a short description in the README on how to setup Ruby/Bundler. This should allow people to test locally when making changes so they can verify if what they are providing actually works.
- Despite these changes the Jekyll _config.yml remains in the root so deployment CI should not be affected.

(I recommend not checking all changed files, review the like 5 top most files which actually change something, the rest are all files moved)

Merge please :D

2022-04-16 20:46 UTC, Thodor12 commented
2nd attempt, however this time we first verify the deployment CI

2022-04-16 22:24 UTC, Thodor12 commented
@OrionDevelopment Could you review the changes to the Dockerfile and docker-compose.
I was able to run a local image using:
```
docker build -t test .
docker run -it --rm -v 'D:\Projects\MinecoloniesWiki:/srv/jekyll' -p "4000:4000" test
```
I just reflected this by adding the volume in the compose, I've not touched the ports since it seems like traefik already handles this.

2022-04-17 05:40 UTC, OrionDevelopment requested changes
You can not use volumes in a cluster setup

2022-04-17 09:50 UTC, OrionDevelopment requested changes

2022-04-17 09:50 UTC, OrionDevelopment commented on docker-compose.yml
> +    ports:
Don't expose ports in the compose.
This is a runtime security risk and not needed.

If you need to modify the port on which our cluster ingress access the container, you need to modify the labels attached to the container.

2022-04-17 09:59 UTC, OrionDevelopment approved these changes
Infrastructure wise this should be fine now.

2022-04-17 17:26 UTC, merged