Plantation hut update
ldtteam/MinecoloniesWiki pull request #795
Opened 2022-04-30 13:31 UTC by Nikademus

Closes #

## Changes proposed:
- Update to plantation hut GUI and content

Merge please :D

2022-04-30 21:06 UTC, Thodor12 requested changes

2022-04-30 21:06 UTC, Thodor12 commented on pages/src/_data/buildinginfo.yml
> +    - name: crop
Please capitalize the setting name

2022-05-01 01:24 UTC, Nikademus commented on pages/src/_data/buildinginfo.yml
> +    - name: crop
ok

2022-05-01 02:38 UTC, anonymous563 approved these changes

2022-05-01 02:38 UTC, merged