Update troubleshooting.md
ldtteam/MinecoloniesWiki pull request #887
Opened 2022-08-21 14:59 UTC by narnianpony

Sometimes, if you upgrade a building without specifying which builder will do it, and the one the system selects has no enough hut level, you don't see the message warning about the lack of level, instead, it puts the tape but the builder never starts.

Closes #

## Changes proposed:
- 
- 

Merge please :D

2022-08-21 14:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ldtteam/MinecoloniesWiki?pullRequest=887) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ldtteam/MinecoloniesWiki?pullRequest=887) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ldtteam/MinecoloniesWiki?pullRequest=887) it.</sub>

2022-08-24 06:46 UTC, anonymous563 requested changes
Capitalize Builder's Hut please
Also, the BH has to be strictly higher than the building you're upgrading

2022-08-24 07:08 UTC, Thodor12 requested changes
Use the building name template, read the README

2022-08-24 14:38 UTC, anonymous563 requested changes
https://github.com/ldtteam/MinecoloniesWiki/pull/887#pullrequestreview-1083270053

As per Thodor's comments, and my oversight, please use the template for building names. This future-proofs the file.

2022-08-27 07:03 UTC, anonymous563 approved these changes

2022-08-27 07:04 UTC, merged