Enchanter doesn't steal XP
ldtteam/MinecoloniesWiki pull request #988
Opened 2023-08-13 17:10 UTC by austinmiller

According to MotionlessTrain on discord, it is no longer the case that
 the enchanter steals XP.

> MotionlessTrain — Today at 12:34 PM
> (They used to steal experience before, but that has been changed later)

I also took pains to clarify the language to the best of my knowledge and organize the data.

Closes #

## Changes proposed:
- 
-

2023-08-13 17:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ldtteam/MinecoloniesWiki?pullRequest=988) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ldtteam/MinecoloniesWiki?pullRequest=988) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ldtteam/MinecoloniesWiki?pullRequest=988) it.</sub>

2023-08-13 18:49 UTC, Thodor12 requested changes

2023-08-13 18:49 UTC, Thodor12 commented on pages/src/source/workers/enchanter.md
> +### Stats
Remove this table please, we don't include this on any page and I'm currently working on better integrating this information into the worker pages.

2023-09-03 19:50 UTC, Thodor12 approved these changes

2023-09-04 14:46 UTC, Thodor12 commented
@anonymous563 this is ready for merge

2023-09-04 14:57 UTC, anonymous563 approved these changes

2023-09-04 14:58 UTC, merged