Update rallyingbanner.md
ldtteam/MinecoloniesWiki pull request #994
Opened 2023-09-05 00:18 UTC by JelliBunn

Add info about the Standard Research to the rallying banner.

The Standard Research, nor it's prereq Telescope doesn't seem to exist in the research pages either. https://wiki.minecolonies.ldtteam.com/source/systems/research

2023-09-05 00:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ldtteam/MinecoloniesWiki?pullRequest=994) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ldtteam/MinecoloniesWiki?pullRequest=994) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ldtteam/MinecoloniesWiki?pullRequest=994) it.</sub>

2023-09-05 06:18 UTC, Thodor12 requested changes
Thanks for this PR, got two small textual changes that I'd like to see modified.

2023-09-05 06:18 UTC, Thodor12 commented on pages/src/source/items/rallyingbanner.md
> +If you have the Standard reserach unlocked, you can "Place" your rallying banner down by right-clicking a Colony Banner.
Typo in "research"

2023-09-05 06:18 UTC, Thodor12 commented on pages/src/source/items/rallyingbanner.md
> +If you have the Standard reserach unlocked, you can "Place" your rallying banner down by right-clicking a Colony Banner.
"... on the ground."

The sentence mentions right clicking, but not on what, so it sounds like you want to right click in the air.

2023-09-24 17:58 UTC, anonymous563 approved these changes

2023-09-24 18:01 UTC, Thodor12 approved these changes

2023-09-24 18:03 UTC, merged